<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Tag;

class TagSeeder extends Seeder
{
  /**
   * Run the database seeds.
   */
  public function run(): void
  {
    $tags = [
      'Mat-Su',
      'Palmer',
      'Wasilla',
      'Butte',
      'Talkeetna',
      'HatcherPass',
      'Knik',
      'Parks',
      'Rivers',
      'Lakes',
      'Glaciers',
      'Mountains',
      'Trails',
      'animals',
      'animals',
      'Forests',
      'Wildlife',
      'Moose',
      'Bear',
      'Dog',
      'Cat',
      'Fox',
      'Wolf',
      'Aurora',
      'NorthernLights',
      'Snow',
      'Ice',
      'Spring',
      'Summer',
      'Fall',
      'Winter',
      'Sunrise',
      'Sunset',
      'Day',
      'Night',
      'Blue',
      'Red',
      'Green',
      'Yellow',
      'White',
      'Black',
      'Brown',
      'Orange',
      'Pink',
      'Purple',
      'Gold',
      'Silver',
      'Sky',
      'Water',
      'Land',
      'Bridge',
      'Road',
      'Highway',
      'Railroad',
      'Airport',
      'Farm',
      'Barn',
      'Tractor',
      'Hay',
      'Corn',
      'Wheat',
      'Market',
      'Festival',
      'Parade',
      'Fair',
      'Concert',
      'Event',
      'Celebration',
      'Ceremony',
      'Interview',
      'Meeting',
      'Workshop',
      'Conference',
      'Election',
      'Voting',
      'Ballot',
      'Mayor',
      'Governor',
      'Senator',
      'Representative',
      'Council',
      'Assembly',
      'Court',
      'Police',
      'Fire',
      'EMS',
      'Rescue',
      'School',
      'College',
      'Library',
      'Books',
      'History',
      'Culture',
      'Art',
      'Painting',
      'Sculpture',
      'Music',
      'Dance',
      'Theater',
      'Film',
      'Photography',
      'Portrait',
      'Landscape',
      'Wildlife',
      'Aerial',
      'Architecture',
      'Building',
      'House',
      'Cabin',
      'Church',
      'Hospital',
      'Store',
      'Mall',
      'Restaurant',
      'Cafe',
      'Bakery',
      'Hotel',
      'Motel',
      'Resort',
      'Campground',
      'Park',
      'Playground',
      'Picnic',
      'BBQ',
      'Fireworks',
      'Sports',
      'Football',
      'Basketball',
      'Baseball',
      'Soccer',
      'Hockey',
      'Skiing',
      'Snowboarding',
      'Fishing',
      'Fish',
      'Hunting',
      'Hiking',
      'Camping',
      'Boating',
      'Kayaking',
      'Canoeing',
      'Rafting',
      'Climbing',
      'Biking',
      'Running',
      'Walking',
      'Jogging',
      'Swimming',
      'Diving',
      'Skating',
      'Surfing',
      'WildlifeRefuge',
      'NatureReserve',
      'Garden',
      'FarmMarket',
      'Tree',
      'Flower',
      'Plant',
      'Leaf',
      'Rock',
      'Soil',
      'Sand',
      'Gravel',
      'Mud',
      'Clay',
      'Fossil',
      'Mineral',
      'Gem',
      'Crystal',
      'Volcano',
      'Wildfire',
      'Forest Fire',
      'Forest',
      'Earthquake',
      'Tsunami',
      'Flood',
      'Fire',
      'Storm',
      'Lightning',
      'Thunder',
      'Rain',
      'Drizzle',
      'Fog',
      'Wind',
      'Breeze',
      'Heat',
      'Cold',
      'Logo',
      'Icon',
      'Construction',
      'People',
      'GIS',
      'Petersville Community Council',
      'Point MacKenzie Community Council',
      'Skwentna Community Council',
      'South Knik River Community Council',
      'South Lakes Community Council',
      'Susitna Community Council',
      'Sutton Community Council',
      'Talkeetna Community Council',
      'Tanaina Community Council',
      'Trapper Creek Community Council',
      'Willow Area Community Organization',
      'Alpine No. 31 RSA',
      'Big Lake No. 21 RSA',
      'Bogard No. 25 RSA',
      'Caswell Lakes No. 15 RSA',
      'Fairview No. 14 RSA',
      'Gold Trail No. 28 RSA',
      'Greater Butte No. 26 RSA',
      'Greater Talkeetna No. 29 RSA',
      'Greater Willow No. 20 RSA',
      'Knik No. 17 RSA',
      'Lazy Mountain No. 19 RSA',
      'Meadow Lakes No. 27 RSA',
      'Midway No. 9 RSA',
      'North Colony No. 23 RSA',
      'South Colony No. 16 RSA',
      'Trapper Creek No. 30 RSA',
      'Butte No. 2 FSA',
      'Caswell No. 135 FSA',
      'Central Mat-Su No. 130 FSA',
      'Greater Palmer Consolidated No. 132 FSA',
      'Sutton No. 4 FSA',
      'Talkeetna No. 24 FSA',
      'West Lakes No. 136 FSA',
      'Willow No. 35 FSA',
      'Chase Trail No. 134 SSA',
      'Circle View & Stampede Estates Flood & Water Erosion Control No. 131 SSA',
      'Talkeetna Flood Control No. 7 SSA',
      'Talkeetna Sewer & Water No. 36 SSA',
      'Assembly District 1',
      'Assembly District 2',
      'Assembly District 3',
      'Assembly District 4',
      'Assembly District 5',
      'Assembly District 6',
      'Assembly District 7',
      'School District 1',
      'School District 2',
      'School District 3',
      'School District 4',
      'School District 5',
      'School District 6',
      'School District 7',
      'Denali State Park Special Land Use District',
      'Hay Flats Recreation Area Special Land Use District',
      'Chickaloon Special Land Use District',
      'Port Mackenzie Special Land Use District',
      'Glacier View Special Land Use District',
      'Sutton Special Land Use District',
      'Talkeetna Special Land Use District',
      'Knik Sled Dog and Recreation Special Land Use District',
      'Dawn Lake Estates #1 Residential Land Use District',
      'Shenandoah Subdivision Residential Land Use District',
      'Kelly Lake Area Residential Land Use District',
      'Woodside Estates Residential Land Use District',
      'Lynne Lake Area Residential Land Use District',
      'Ancient Tree Estates #1 Residential Land Use District',
      'Pinnacle Mountain Subdivision Residential Land Use District',
      'Nancy Lake Northwest Shore Residential Land Use District',
      'Nancy Lake Northeast Shore Residential Land Use District',
      'Alaska Railroad Curry Quarry Interim Materials Districts',
      'Alsop Pit Interim Materials Districts',
      'Dirtworks Interim Materials Districts',
      'Kopczenski Pit Interim Materials Districts',
      'Mass Excavation Interim Materials Districts',
      'Mile 78.3 Kashwitna Interim Materials Districts',
      'Section 9 Pit Interim Materials Districts',
      'Seven Mile Ridge Interim Materials Districts',
      'Canoe Lake Subdivision Single Family Land Use District',
      'Chugach View Estates Single Family Land Use District',
      'Wilderness Subdivision Single Family Land Use District',
      'Light Wood Subdivision Large Lot Single Family Residential Land Use District',
      'Wolf Lake Airport Overlay District',
    ];

    foreach ($tags as $tag) {
      Tag::firstOrCreate(['name' => $tag]);
    }
  }
}
