services:
  typesense:
    image: typesense/typesense:26.0
    restart: on-failure
    ports:
      - '8108:8108'
    volumes:
      - ./typesense-data:/data
    command: '--data-dir /data --api-key=xyz --enable-cors'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: blueharvest
    container_name: blueharvest
    restart: unless-stopped
    tty: true
    env_file:
      - .env
    volumes:
      - ./:/var/www
      - ./storage:/var/www/storage
      - ./bootstrap/cache:/var/www/bootstrap/cache
      - ./scripts:/scripts
    networks:
      - app-network
    depends_on:
      - mysql
    entrypoint: ['/scripts/entrypoint.sh']

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - '8080:80'
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - app

  mysql:
    image: mysql:5.7
    container_name: blueharvest-mysql
    restart: unless-stopped
    tty: true
    ports:
      - '3306:3306'
    env_file:
      - .env
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

volumes:
  mysql-data:
    driver: local

networks:
  app-network:
    driver: bridge
