services:
  app:
    image: freedomsmb/blueharvest:latest
    ports:
      - '9000:9000'
    container_name: blueharvest
    restart: unless-stopped
    tty: true
    env_file:
      - .env
    volumes:
      - ./:/var/www
      - ./storage:/var/www/storage
      - ./bootstrap/cache:/var/www/bootstrap/cache

  typesense:
    image: typesense/typesense:26.0
    restart: on-failure
    ports:
      - '8108:8108'
    volumes:
      - ./typesense-data:/data
    command: '--data-dir /data --api-key=xyz --enable-cors'

  nginx:
    image: nginx:latest
    volumes:
      - .:/var/www
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
    depends_on:
      - app
