/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ApplicationLogo: typeof import('./Components/ApplicationLogo.vue')['default']
    AuthenticatedLayout: typeof import('./Layouts/AuthenticatedLayout.vue')['default']
    AuthLayout: typeof import('./Layouts/AuthLayout.vue')['default']
    CCard: typeof import('./Components/Surfaces/CCard/CCard.vue')['default']
    CCardTitle: typeof import('./Components/Surfaces/CCard/CCardTitle.vue')['default']
    Checkbox: typeof import('./Components/Checkbox.vue')['default']
    CoreAppBar: typeof import('./Components/nav/CoreAppBar.vue')['default']
    CoreLayout: typeof import('./Layouts/CoreLayout.vue')['default']
    DangerButton: typeof import('./Components/DangerButton.vue')['default']
    DragDropFileInput: typeof import('./Components/Form/DragDropFileInput.vue')['default']
    Dropdown: typeof import('./Components/Dropdown.vue')['default']
    DropdownLink: typeof import('./Components/DropdownLink.vue')['default']
    Header2: typeof import('./Components/Typography/Header2.vue')['default']
    IArrowUpTray: typeof import('./Components/icons/IArrowUpTray.vue')['default']
    ImageCard: typeof import('./Components/Surfaces/ImageCard/ImageCard.vue')['default']
    InputError: typeof import('./Components/InputError.vue')['default']
    InputLabel: typeof import('./Components/InputLabel.vue')['default']
    Logo: typeof import('./Components/Icons/Logo.vue')['default']
    MobileDrawer: typeof import('./Components/nav/MobileDrawer.vue')['default']
    Modal: typeof import('./Components/Modal.vue')['default']
    NavigationMenu: typeof import('./Components/nav/NavigationMenu.vue')['default']
    NavLink: typeof import('./Components/NavLink.vue')['default']
    NavTabs: typeof import('./Components/nav/NavTabs.vue')['default']
    PageContainer: typeof import('./Components/layout/PageContainer.vue')['default']
    PasswordInput: typeof import('./Components/Form/PasswordInput.vue')['default']
    PrimaryButton: typeof import('./Components/PrimaryButton.vue')['default']
    ResponsiveNavLink: typeof import('./Components/ResponsiveNavLink.vue')['default']
    SecondaryButton: typeof import('./Components/SecondaryButton.vue')['default']
    SelectField: typeof import('./Components/Form/SelectField.vue')['default']
    SimpleAutoComplete: typeof import('./Components/Form/SimpleAutoComplete.vue')['default']
    TextField: typeof import('./Components/Form/TextField.vue')['default']
    TextInput: typeof import('./Components/TextInput.vue')['default']
    ThemeToggle: typeof import('./Components/ThemeToggle.vue')['default']
    ThemeToggleBtn: typeof import('./Components/ThemeToggle.vue')['default']
    ToastStack: typeof import('./Components/ToastStack.vue')['default']
    UserMenu: typeof import('./Components/nav/UserMenu.vue')['default']
  }
}
