name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-west-2
  EB_APP_NAME: ${{ secrets.EB_APP_NAME }}
  EB_ENV_NAME: ${{ secrets.EB_ENV_NAME }}
  AWS_DEPLOYER_ROLE_ARN: ${{ secrets.AWS_DEPLOYER_ROLE_ARN }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up docker Buildx for build caching.
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        run: |
          echo ${{env.DOCKER_PASSWORD}} | docker login -u ${{ env.DOCKER_USERNAME }} --password-stdin

      - name: Cache Docker Layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          content: .
          push: true
          tags: freedomsmb/blueharvest:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_DEPLOYER_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install Elastic Beanstalk CLI
        run: |
          pip install awsebcli

      - name: Initialize Elastic Beanstalk
        run: |
          eb init -p docker ${{ env.EB_APP_NAME }}" --region ${{ env.AWS_REGION }}

      - name: Deploy to Elastic Beanstalk
        run: |
          eb create "${{ env.EB_ENV_NAME }}" --cfg default --timeout 15 --platform "docker-compose" || eb deploy
